# Generated by Django 4.1.2 on 2023-09-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.TextField(default='username', unique=True, verbose_name='User Name'),
        ),
    ]
