# Generated by Django 4.2.4 on 2023-08-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='tag for title...', max_length=60),
        ),
    ]
