# Generated by Django 4.2.4 on 2023-08-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner_img',
            field=models.CharField(default='https://i.ibb.co/qgbtz4x/black-hole-1.png', max_length=225),
        ),
    ]
