# Generated by Django 4.2.4 on 2023-08-29 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0003_post_banner_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
