# Generated by Django 4.2.4 on 2023-09-02 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0005_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_access_dashboard', 'Can access the dashboard')]},
        ),
    ]
