# Generated by Django 4.2.4 on 2023-09-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
