# Generated by Django 4.2.4 on 2023-09-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0011_alter_post_snippet_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Github',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/admin/profile'),
        ),
    ]
