# Generated by Django 4.2.4 on 2023-09-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0012_profile_github_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Github',
        ),
    ]
