# Generated by Django 4.1.2 on 2023-09-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0016_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
