# Generated by Django 4.1.2 on 2023-09-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0017_remove_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='...', max_length=60),
        ),
    ]
