# Generated by Django 4.2.4 on 2023-09-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0019_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
