# Generated by Django 4.2.4 on 2023-09-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0020_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/admin/profile/profile_default.png', null=True, upload_to='images/admin/profile'),
        ),
    ]
